/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class umontreal_iro_lecuyer_util_GlobalCPUTimeChrono */

#ifndef _Included_umontreal_iro_lecuyer_util_GlobalCPUTimeChrono
#define _Included_umontreal_iro_lecuyer_util_GlobalCPUTimeChrono
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: ssjUtilLoaded */
/*
 * Class:     umontreal_iro_lecuyer_util_GlobalCPUTimeChrono
 * Method:    Heure
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_umontreal_iro_lecuyer_util_GlobalCPUTimeChrono_Heure
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
