#!/bin/csh

setenv SSJHOME <SSJ home path>/ssj-2

# For LaTex documentation of package charts, packages tikz and pgf
setenv PGFLIBRARY <path to pgf>/tex/pgf-2.00

if ( ! $?SSJHOME ) then
    echo "You must set SSJHOME before calling this script."
    exit
endif

if ( ! $?CLASSPATH ) then
    setenv CLASSPATH
endif
if ( ! $?LD_LIBRARY_PATH ) then
    setenv LD_LIBRARY_PATH
endif
if ( ! $?TEXINPUTS ) then
   setenv TEXINPUTS
endif

setenv CLASSPATH .:$SSJHOME/lib/ssj.jar:$SSJHOME/lib/colt.jar:$SSJHOME/lib/tcode.jar:$CLASSPATH

setenv TEXINPUTS .:$SSJHOME/source:$PGFLIBRARY//:$TEXINPUTS

switch ( "`uname -m`" )
   case 'i686':
   setenv LD_LIBRARY_PATH $SSJHOME/lib:$LD_LIBRARY_PATH
   breaksw

   case 'x86_64':
   setenv LD_LIBRARY_PATH $SSJHOME/lib64:$LD_LIBRARY_PATH
   breaksw
endsw

alias cdssj 'cd $SSJHOME/\!*'
alias cdssjsrc 'cd $SSJHOME/source/umontreal/iro/lecuyer/\!*'

